server:
  port: 8091
spring:
  application:
    name: Reports
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    mongodb:
      uri:mongodb+srv://Rajesh:Rajesh@hms.s1qzi.mongodb.net/test
      database:Reports_Microservice
